### PR TITLE
Platform uplift

### PR DESCRIPTION
**Pull request by oobedan**
- ABAC updates include:
ABACs uplift and alignment
(#76 issue guest invite correction)
(#83 issue MFA for browser access) 
Conditional Access ABAC updates
- Platform Updates:
Tenant restrictions
Update guidance for Zero Trust model (commit https://github.com/govau/desktop.gov.au/commit/70964494bda9a0a0d04557e353500efec816f3ba)
Provide some guidance around M365 group naming schemes
Terms of Use guidance 
Self Service signup - Self-service sign-up for email-verified users (prevents GovTeams issue for new tenants)
Backups guidance (consider 3rd party)
Essential 8 alignment
AD Connect requirements update
AD display name guidance
PIM updates
Corrected ATP group names

### CODE REVIEW

**Comment by zedzedzed** [comment]
Reading the pull request description:

* Curious to know if there's more that has been updated for zero trust other than this commit https://github.com/govau/desktop.gov.au/pull/92/commits/70964494bda9a0a0d04557e353500efec816f3ba
* Also can you link me to `M365 group lockdown script`? I may have missed it.

Everything else looks good.

**Comment by oobedan** [comment]
> Reading the pull request description:
> 
> * Curious to know if there's more that has been updated for zero trust other than this commit [7096449](https://github.com/govau/desktop.gov.au/commit/70964494bda9a0a0d04557e353500efec816f3ba)
> * Also can you link me to `M365 group lockdown script`? I may have missed it.
> 
> Everything else looks good.

Line 273 on platform, guidance on avoidance of using trusted IPs.

Group Lockdown Script is a code block  -> https://github.com/oobedan/desktop.gov.au/blob/platform-uplift/blueprint/abac/platform.md#delegate-office-365-group-creation

**Comment by zedzedzed** [comment]
> Group Lockdown Script is a code block -> https://github.com/oobedan/desktop.gov.au/blob/platform-uplift/blueprint/abac/platform.md#delegate-office-365-group-creation

The code block appears to have been introduced in a different pull request (#88). This pull request (#92) includes a single line change `o365groupcreator` -> `o365groupcreators`. Can you confirm that is correct? I'm just making sure there aren't any missing content.

**Comment by oobedan** [comment]
@zedzedzed ah yes you're correct.. I had a typo in the group name to create and what the script was calling.

**Review by zedzedzed — APPROVED** [review]

**Pull request merged**
