### PR TITLE
Intune - Builtin\administrators web and outlook executables lockdown

### PR DESCRIPTION
**Pull request by oobedan**
Updates include: (intune configuration for both implementation types)
- Provide a method to prohibit local admins from using common web browsers and outlook, using Applocker CSP, aligning to Essential 8 guidance "Privileged accounts (excluding privileged service accounts) are prevented from accessing the internet, email and web services"

### CODE REVIEW

**Comment by zedzedzed** [comment]
I think this change needs to be supported by guidance on how the admin can go ahead and do their legitimate business without access to emails (eg system notifications, alerts) and the internet. I don't mind if it's indicating a particular standard practice, it just needs to be mentioned so that we fully inform our users that there may be breaking changes ahead to their existing implementations.

**Comment by zedzedzed** [comment]
It could be as a warning paragraph and linking back to the new secure administration section that will be introduced in https://github.com/govau/desktop.gov.au/pull/80 ?

**Comment by oobedan** [comment]
@zedzedzed have updated link back with a warning to review the guiadance.

**Comment by zedzedzed** [comment]
Looks good now. I extracted the long XML content and placed it into its own file. When loading in Firefox, it doesn't think it's valid XML as there's no single root element. Is the XML whole or is it missing things like those in the following example https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp#recommended-deny-list-for-windows-information-protection

**Comment by oobedan** [comment]
> Looks good now. I extracted the long XML content and placed it into its own file. When loading in Firefox, it doesn't think it's valid XML as there's no single root element. Is the XML whole or is it missing things like those in the following example https://docs.microsoft.com/en-us/windows/client-management/mdm/applocker-csp#recommended-deny-list-for-windows-information-protection

It is extracted directly outside of a local applocker export which supports copy and paste directly into the CSP window.

**Review by zedzedzed — APPROVED** [review]

**Pull request merged**
